banner: |
    â–ˆâ–ˆâ–ˆâ–ˆâ–ˆ  â–ˆâ–ˆâ–ˆ  â–ˆâ–ˆâ–ˆâ–ˆ  â–ˆ   â–ˆ  â–ˆâ–ˆâ–ˆ  â–ˆâ–ˆâ–ˆâ–ˆ
      â–ˆ   â–ˆ   â–ˆ â–ˆ   â–ˆ â–ˆ   â–ˆ   â–ˆ  â–ˆ    
      â–ˆ   â–ˆâ–ˆâ–ˆâ–ˆâ–ˆ â–ˆâ–ˆâ–ˆâ–ˆ  â–ˆ   â–ˆ   â–ˆ   â–ˆâ–ˆâ–ˆ 
    â–ˆ â–ˆ   â–ˆ   â–ˆ â–ˆ  â–ˆ   â–ˆ â–ˆ    â–ˆ      â–ˆ
     â–ˆâ–ˆ   â–ˆ   â–ˆ â–ˆ   â–ˆ   â–ˆ    â–ˆâ–ˆâ–ˆ  â–ˆâ–ˆâ–ˆâ–ˆ
# åœ°å€: https://github.com/Jarv1s0/Proxy_Script
# ç‰ˆæœ¬: v2.2.1
# æ›´æ–°: 2026 å¹´ 3 æœˆ 2 æ—¥

# ==================== æ ¸å¿ƒé…ç½® ====================
# åŸºç¡€é…ç½®
mode: rule
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
allow-lan: true
unified-delay: true
tcp-concurrent: true
log-level: warning
bind-address: '*'
find-process-mode: 'always'
keep-alive-interval: 15
keep-alive-idle: 600

# TUNæ¨¡å¼é…ç½®
tun:
  enable: true
  stack: gvisor
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
    
# DNSé…ç½®
dns:
  enable: true
  respect-rules: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  # è§£æä¸Šæ¸¸ DoH/DoT çš„èµ·å§‹ DNS
  default-nameserver:
    - tls://223.5.5.5
    - tls://223.6.6.6
  # ä»£ç†è·¯å¾„ç”¨çš„å›½å¤–ä¸Šæ¸¸ï¼ˆä»…å¯¹éœ€ä»£ç†çš„éç›´è¿è§„åˆ™é›†åŸŸåï¼‰
  nameserver:
    - "https://1.1.1.1/dns-query"
    - "https://8.8.8.8/dns-query"
  # ç›´è¿è·¯å¾„ä¸“ç”¨ä¸Šæ¸¸ï¼ˆå›½å†… DoHï¼‰
  direct-nameserver:
    - "https://dns.alidns.com/dns-query"
    - "https://doh.pub/dns-query"
  # è§£æä»£ç†æœåŠ¡å™¨çš„åŸŸåï¼Œé˜²å¾ªç¯ç”¨å›½å†…
  proxy-server-nameserver:
    - "https://dns.alidns.com/dns-query"
    - "https://doh.pub/dns-query"
  # é…ç½®æŸ¥è¯¢è®¿é—®åŸŸåä½¿ç”¨çš„æœåŠ¡å™¨
  nameserver-policy:
    # ç›´è¿ç±»è§„åˆ™é›†åŒ¹é…çš„åŸŸåç»‘å®šå›½å†…ä¸Šæ¸¸ï¼Œé¦–è·³å³å›½å†…ï¼Œä¸è§¦å‘å›½å¤–â†’å›½å†…å›åˆ‡
    "rule-set:Direct,Private,China,fakeip-filter":
      - "https://dns.alidns.com/dns-query"
      - "https://doh.pub/dns-query"
  fake-ip-filter:
    - rule-set:Direct
    - rule-set:Private
    - rule-set:China
    - rule-set:fakeip-filter
  
# å®éªŒæ€§åŠŸèƒ½
experimental:
  quic-go-disable-gso: true  
  
# é…ç½®å­˜å‚¨
profile:
  store-selected: true
  store-fake-ip: true

# æµé‡å—…æ¢
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"
    - "+.push.apple.com"
    
 # ==================== é”šç‚¹é…ç½® ====================   
# é”šç‚¹å®šä¹‰
UrlTest: &UrlTest {type: url-test, interval: 200, lazy: true, url: 'https://www.google.com/generate_204', hidden: true, include-all: true }
Select: &Select { type: select, hidden: false, include-all: true }
Global_settings: { exclude_regex: &global_exclude "AHK|æ’é™¤1|æ’é™¤2|5x|å‰©ä½™æµé‡|è¿‡æœŸ|å›å›½|ç¾¤|å®˜ç½‘|å®¢æœ|è®¢é˜…|æµé‡" }
# åœ°ç†ä½ç½®åŒ¹é…é”šç‚¹
filters:
  - &FilterHK '(?i)æ¸¯|ğŸ‡­ğŸ‡°|HK|Hong|HKG'
  - &FilterSG '(?i)å¡|ğŸ‡¸ğŸ‡¬|SG|Sing|SIN|XSP'
  - &FilterJP '(?i)æ—¥|ğŸ‡¯ğŸ‡µ|JP|Japan|NRT|HND|KIX|CTS|FUK'
  - &FilterKR '(?i)éŸ©|ğŸ‡°ğŸ‡·|éŸ“|é¦–å°”|KR|KOR|Korea'
  - &FilterUS '(?i)ç¾|ğŸ‡ºğŸ‡¸|\bUS\b|USA|SJC|JFK|LAX|ORD|SFO'
  - &FilterTW '(?i)å°|ğŸ‡¹ğŸ‡¼|TW|tai|TPE|TSA|KHH'
  - &FilterEU '(?i)å¾·|æ³•|è‹±|æ„|è·|ç‘|ğŸ‡ªğŸ‡º|FRA|CDG|LHR|AMS'

# ==================== ä»£ç†ç­–ç•¥ç»„ ====================
#ä»£ç†ç»„
proxy-groups:
  # --- é¡¶å±‚ä¸šåŠ¡åˆ†ç»„ ---
  - { name: Proxy, type: select, proxies: [é¦™æ¸¯, å°æ¹¾, æ—¥æœ¬, æ–°åŠ å¡, ç¾å›½, éŸ©å›½, æ¬§ç›Ÿ, ALL, DIRECT], icon: https://cdn.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Rocket.png }
  - { name: YouTube, type: select, proxies: [ç¾å›½, é¦™æ¸¯, å°æ¹¾, æ—¥æœ¬, æ–°åŠ å¡, éŸ©å›½, æ¬§ç›Ÿ], icon: https://cdn.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/YouTube.png }
  - { name: AI, type: select, proxies: [ç¾å›½, æ–°åŠ å¡, æ—¥æœ¬, æ¬§ç›Ÿ], icon: https://cdn.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/AI.png }
  - { name: Games, type: select, proxies: [é¦™æ¸¯, å°æ¹¾, æ—¥æœ¬, æ–°åŠ å¡, ç¾å›½, DIRECT], icon: https://cdn.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Steam.png }
  - { name: Google, type: select, proxies: [ç¾å›½, é¦™æ¸¯, å°æ¹¾, æ—¥æœ¬, æ–°åŠ å¡, éŸ©å›½, æ¬§ç›Ÿ], icon: https://cdn.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Google_Search.png } 
  - { name: GitHub, type: select, proxies: [é¦™æ¸¯, å°æ¹¾, æ—¥æœ¬, æ–°åŠ å¡, ç¾å›½, éŸ©å›½, æ¬§ç›Ÿ], icon: https://cdn.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/GitHub.png }
  - { name: Telegram, type: select, proxies: [é¦™æ¸¯, å°æ¹¾, æ—¥æœ¬, æ–°åŠ å¡, ç¾å›½, éŸ©å›½, æ¬§ç›Ÿ], icon: https://cdn.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Telegram.png }

  # --- åº•å±‚åœ°åŒºç­›é€‰ç»„ ---
  - { name: é¦™æ¸¯, <<: *UrlTest, filter: *FilterHK, exclude-filter: *global_exclude, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Hong_Kong.png }
  - { name: å°æ¹¾, <<: *UrlTest, filter: *FilterTW, exclude-filter: *global_exclude, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Taiwan.png }
  - { name: æ—¥æœ¬, <<: *UrlTest, filter: *FilterJP, exclude-filter: *global_exclude, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Japan.png }
  - { name: æ–°åŠ å¡, <<: *UrlTest, filter: *FilterSG, exclude-filter: *global_exclude, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Singapore.png }
  - { name: éŸ©å›½, <<: *UrlTest, filter: *FilterKR, exclude-filter: *global_exclude, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Korea.png }
  - { name: ç¾å›½, <<: *Select, filter: *FilterUS, exclude-filter: *global_exclude, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/United_States.png }
  - { name: æ¬§ç›Ÿ, <<: *UrlTest, filter: *FilterEU, exclude-filter: *global_exclude, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/European_Union.png } 
  - { name: ALL, type: select, include-all: true, exclude-filter: *global_exclude, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Global.png }

# ==================== è§„åˆ™é›† ====================
# è§„åˆ™é›†è¡Œä¸ºæ¨¡æ¿
BehaviorDN: &BehaviorDN {type: http, behavior: domain, format: mrs, interval: 86400, proxy: Proxy}
BehaviorIP: &BehaviorIP {type: http, behavior: ipcidr, format: mrs, interval: 86400, proxy: Proxy}

# è§„åˆ™æä¾›è€…
rule-providers:  
  # åŸŸåè§„åˆ™
  Tracking:       {<<: *BehaviorDN, url: https://github.com/666OS/rules/raw/release/mihomo/domain/Tracking.mrs}
  Advertising:    {<<: *BehaviorDN, url: https://github.com/666OS/rules/raw/release/mihomo/domain/Advertising.mrs} 
  Direct:         {<<: *BehaviorDN, url: https://github.com/666OS/rules/raw/release/mihomo/domain/Direct.mrs}
  Private:        {<<: *BehaviorDN, url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/private.mrs}
  Download:       {<<: *BehaviorDN, url: https://github.com/666OS/rules/raw/release/mihomo/domain/Download.mrs}
  fakeip-filter:  {<<: *BehaviorDN, url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/fakeip-filter.mrs}
  AI:             {<<: *BehaviorDN, url: https://github.com/666OS/rules/raw/release/mihomo/domain/AI.mrs} 
  GitHub:         {<<: *BehaviorDN, url: https://github.com/666OS/rules/raw/release/mihomo/domain/GitHub.mrs}    
  Telegram:       {<<: *BehaviorDN, url: https://github.com/666OS/rules/raw/release/mihomo/domain/Telegram.mrs}
  SteamCN:        {<<: *BehaviorDN, url: https://raw.githubusercontent.com/Jarv1s0/RuleList/refs/heads/release/SteamCN.mrs} 
  Games:          {<<: *BehaviorDN, url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/games.mrs}
  YouTube:        {<<: *BehaviorDN, url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/youtube.mrs}
  AppleCN:        {<<: *BehaviorDN, url: https://github.com/666OS/rules/raw/release/mihomo/domain/AppleCN.mrs}
  GoogleCN:       {<<: *BehaviorDN, url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/google-cn.mrs}
  Google:         {<<: *BehaviorDN, url: https://github.com/666OS/rules/raw/release/mihomo/domain/Google.mrs}
  Microsoft:      {<<: *BehaviorDN, url: https://github.com/666OS/rules/raw/release/mihomo/domain/Microsoft.mrs}
  GFW:            {<<: *BehaviorDN, url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/gfw.mrs}    
  Proxy:          {<<: *BehaviorDN, url: https://github.com/666OS/rules/raw/release/mihomo/domain/Proxy.mrs}
  China:          {<<: *BehaviorDN, url: https://github.com/666OS/rules/raw/release/mihomo/domain/China.mrs}
  # IPè§„åˆ™
  AdvertisingIP:  {<<: *BehaviorIP, url: https://github.com/666OS/rules/raw/release/mihomo/ip/Advertising.mrs}
  PrivateIP:      {<<: *BehaviorIP, url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/privateip.mrs}
  AIIP:           {<<: *BehaviorIP, url: https://github.com/666OS/rules/raw/release/mihomo/ip/AI.mrs}
  TelegramIP:     {<<: *BehaviorIP, url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/telegramip.mrs}   
  GoogleIP:       {<<: *BehaviorIP, url: https://github.com/666OS/rules/raw/release/mihomo/ip/Google.mrs}  
  ProxyIP:        {<<: *BehaviorIP, url: https://github.com/666OS/rules/raw/release/mihomo/ip/Proxy.mrs} 
  ChinaIP:        {<<: *BehaviorIP, url: https://github.com/666OS/rules/raw/release/mihomo/ip/China.mrs}
  
# ==================== è§„åˆ™è·¯ç”± ====================  
rules:
  # 1. ä¼˜å…ˆå¤„ç†ç‰¹å®šåŸŸåå…³é”®å­— (DomainSet/Keyword)
  - DOMAIN-KEYWORD,1ytsub,DIRECT
  - DOMAIN-KEYWORD,jarv1s,Proxy
  - PROCESS-NAME,dota2.exe,DIRECT
  - PROCESS-NAME,language_server_windows_x64.exe,AI # Antigravity
  - PROCESS-NAME,Antigravity.exe,AI # Antigravity 
  # æ‹¦æˆªè§„åˆ™
  - RULE-SET,Tracking,REJECT
  - RULE-SET,Advertising,REJECT
  - OR,((AND,((DST-PORT,443),(NETWORK,UDP),(NOT,((GEOIP,CN))))),(DST-PORT,853)),REJECT # æ‹¦æˆªæµ·å¤– QUIC æµé‡åŠå…¨åŸŸ DoT æµé‡
  # åŸŸåè§„åˆ™
  - RULE-SET,Private,DIRECT
  - RULE-SET,Direct,DIRECT
  - RULE-SET,SteamCN,DIRECT
  - RULE-SET,Download,DIRECT
  - RULE-SET,AppleCN,DIRECT
  - RULE-SET,AI,AI
  - RULE-SET,GitHub,GitHub
  - RULE-SET,Telegram,Telegram
  - RULE-SET,Games,Games
  - RULE-SET,YouTube,YouTube
  - RULE-SET,Microsoft,DIRECT
  - RULE-SET,Google,Google
  - RULE-SET,GoogleCN,Google
  - RULE-SET,GFW,Proxy
  - RULE-SET,Proxy,Proxy
  - RULE-SET,China,DIRECT
  # IPè§„åˆ™
  - RULE-SET,AdvertisingIP,REJECT,no-resolve
  - RULE-SET,PrivateIP,DIRECT,no-resolve
  - RULE-SET,AIIP,AI,no-resolve
  - RULE-SET,TelegramIP,Telegram,no-resolve
  - RULE-SET,GoogleIP,Google,no-resolve
  - RULE-SET,ProxyIP,Proxy,no-resolve
  - RULE-SET,ChinaIP,DIRECT
  - MATCH,Proxy
